[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-8_x", "bash"]

[phases.install]
cmds = ["node --version", "npm --version", "npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run railway:start"